### ISSUE TITLE
Belgium - Flanders - Brussels

### ISSUE THREAD

**Issue by uncentral** [mapnificent/mapnificent_cities#11]
Could you add all transport companies in Belgium? You already added Flanders, but trains and some buses are not in the calculations.

You can find their GTFS feeds here:
http://transitfeeds.com/l/382-belgium

You will also find the 3 bus companies that operate around an in Belgium/Flanders/Brussels (of which you already added De Lijn).

**Comment by stefanw** [comment]
I removed Flanders in favour of [Mapnificent Belgium](https://www.mapnificent.net/belgium/). However, hunting down licenses for all services did not work out and I'm not happy with the non-standard license of STIBB.
