### ISSUE TITLE
Add Nancy - France

### ISSUE THREAD

**Issue by MatthieuCoelho** [mapnificent/mapnificent_cities#15]
The GTFS feed for Nancy is at 
http://www.bkk.hu/apps/gtfs/
http://opendata.grandnancy.eu/jeux-de-donnees/detail-dune-fiche-de-donnees/?tx_icsoddatastore_pi1%5Bpage%5D=3&tx_icsoddatastore_pi1%5Buid%5D=108&tx_icsoddatastore_pi1%5BreturnID%5D=447

**Comment by stefanw** [comment]
[Mapnificent Nancy](https://www.mapnificent.net/nancy) is now online, based on the [Transitfeeds.com info](http://transitfeeds.com/l/446-nancy-france).
