### ISSUE TITLE
Add Palermo

### ISSUE THREAD

**Issue by patperu** [mapnificent/mapnificent_cities#2]
Data is here:  :wink:

https://github.com/openamat/Official-Data/raw/master/amat_feed_gtfs_v8.zip

**Comment by stefanw** [comment]
[Mapnificent Palermo](https://www.mapnificent.net/palermo/) is now online!

**Comment by aborruso** [comment]
Wow, thank you stefanw!!

Only a note: that one is an old version of the dataset. The URL corresponding always to the latest version of it (and moreover the official one) is this https://www.comune.palermo.it/gtfs/amat_feed_gtfs.zip

Please, if you have the time update you great work.

Thank you
