### ISSUE TITLE
Cleveland Ohio USA data is missing trains

### ISSUE THREAD

**Issue by peterdietz** [mapnificent/mapnificent_cities#3]
First, very impressive project. I've been trying to understand the code. 

I believe that the data for Cleveland Ohio USA is omitting some of the routes. It looks like only the bus system is being tracked, but not the train lines. Here is the location for Cleveland's GTFS:
http://www.riderta.com/sites/default/files/gtfs/latest/google_transit.zip

If you look at the Red Line (in my opinion the best train line in CLE) you would be able to connect from downtown to the airport with a half hour (it also touches west side, and east side). 
![cleveland-gtfs-redline](https://cloud.githubusercontent.com/assets/58014/12723903/7f05a678-c8d9-11e5-86d9-6b68b4dc2bb7.png)

However, mapnificent doesn't have the type of spread. 
![cleveland-mapnificent-30m](https://cloud.githubusercontent.com/assets/58014/12723893/770af91e-c8d9-11e5-879c-3d760e01bc51.png)

So, I'm guessing that the latest GTFS just needs to be recompiled, or perhaps these were somehow missing.

**Comment by stefanw** [comment]
Hi, I just updated Cleveland, but it still seems to miss that train line. It could be that the service is detected as not very frequent which will make it appear later than perhaps reasonable. I will look into it.

**Comment by stefanw** [comment]
I think this has been addressed in the last release:
https://www.mapnificent.net/cleveland/

**Comment by peterdietz** [comment]
👍 Thank you @stefanw, the map looks correct, with respect to the train data now being in there. I looked for being able to get between downtown and the airport within a half hour, and the general shape of the train line spreading from downtown. Thanks again, good job.
