### ISSUE TITLE
How to add a new city?

### ISSUE THREAD

**Issue by e3krisztian** [mapnificent/mapnificent_cities#5]
I would like to have a city added, that was once working (Budapest, a picture of mapnificent/budapest working is at http://www.citylab.com/commute/2012/05/30-minutes-transit-20-world-cities/2033/)

Could you explain
- what is inside the `data/`_city_`/`_city_`.json` file?
- how to create this json file?

**Comment by stefanw** [comment]
I updated the README to better explain the process.
