### ISSUE TITLE
Add Budapest

### ISSUE THREAD

**Issue by e3krisztian** [mapnificent/mapnificent_cities#6]
The GTFS feed for Budapest is at http://www.bkk.hu/apps/gtfs/

**Comment by stefanw** [comment]
Done! https://www.mapnificent.net/budapest/

**Comment by majdnemkocka** [comment]
Dear Stefan,

Thank you so much!

- Kristóf

On Sat, Sep 16, 2017 at 12:17 AM, Stefan Wehrmeyer <notifications@github.com
